// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.keycloak.openid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClientScopeArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClientScopeArgs Empty = new ClientScopeArgs();

    @Import(name="consentScreenText")
    private @Nullable Output<String> consentScreenText;

    public Optional<Output<String>> consentScreenText() {
        return Optional.ofNullable(this.consentScreenText);
    }

    @Import(name="description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="guiOrder")
    private @Nullable Output<Integer> guiOrder;

    public Optional<Output<Integer>> guiOrder() {
        return Optional.ofNullable(this.guiOrder);
    }

    @Import(name="includeInTokenScope")
    private @Nullable Output<Boolean> includeInTokenScope;

    public Optional<Output<Boolean>> includeInTokenScope() {
        return Optional.ofNullable(this.includeInTokenScope);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="realmId", required=true)
    private Output<String> realmId;

    public Output<String> realmId() {
        return this.realmId;
    }

    private ClientScopeArgs() {}

    private ClientScopeArgs(ClientScopeArgs $) {
        this.consentScreenText = $.consentScreenText;
        this.description = $.description;
        this.guiOrder = $.guiOrder;
        this.includeInTokenScope = $.includeInTokenScope;
        this.name = $.name;
        this.realmId = $.realmId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClientScopeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClientScopeArgs $;

        public Builder() {
            $ = new ClientScopeArgs();
        }

        public Builder(ClientScopeArgs defaults) {
            $ = new ClientScopeArgs(Objects.requireNonNull(defaults));
        }

        public Builder consentScreenText(@Nullable Output<String> consentScreenText) {
            $.consentScreenText = consentScreenText;
            return this;
        }

        public Builder consentScreenText(String consentScreenText) {
            return consentScreenText(Output.of(consentScreenText));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder guiOrder(@Nullable Output<Integer> guiOrder) {
            $.guiOrder = guiOrder;
            return this;
        }

        public Builder guiOrder(Integer guiOrder) {
            return guiOrder(Output.of(guiOrder));
        }

        public Builder includeInTokenScope(@Nullable Output<Boolean> includeInTokenScope) {
            $.includeInTokenScope = includeInTokenScope;
            return this;
        }

        public Builder includeInTokenScope(Boolean includeInTokenScope) {
            return includeInTokenScope(Output.of(includeInTokenScope));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder realmId(Output<String> realmId) {
            $.realmId = realmId;
            return this;
        }

        public Builder realmId(String realmId) {
            return realmId(Output.of(realmId));
        }

        public ClientScopeArgs build() {
            if ($.realmId == null) {
                throw new MissingRequiredPropertyException("ClientScopeArgs", "realmId");
            }
            return $;
        }
    }

}
