// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ldap

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-keycloak/sdk/v4/go/keycloak"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "keycloak:ldap/fullNameMapper:FullNameMapper":
		r = &FullNameMapper{}
	case "keycloak:ldap/groupMapper:GroupMapper":
		r = &GroupMapper{}
	case "keycloak:ldap/hardcodedGroupMapper:HardcodedGroupMapper":
		r = &HardcodedGroupMapper{}
	case "keycloak:ldap/hardcodedRoleMapper:HardcodedRoleMapper":
		r = &HardcodedRoleMapper{}
	case "keycloak:ldap/msadLdsUserAccountControlMapper:MsadLdsUserAccountControlMapper":
		r = &MsadLdsUserAccountControlMapper{}
	case "keycloak:ldap/msadUserAccountControlMapper:MsadUserAccountControlMapper":
		r = &MsadUserAccountControlMapper{}
	case "keycloak:ldap/roleMapper:RoleMapper":
		r = &RoleMapper{}
	case "keycloak:ldap/userAttributeMapper:UserAttributeMapper":
		r = &UserAttributeMapper{}
	case "keycloak:ldap/userFederation:UserFederation":
		r = &UserFederation{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := keycloak.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/fullNameMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/groupMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/hardcodedGroupMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/hardcodedRoleMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/msadLdsUserAccountControlMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/msadUserAccountControlMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/roleMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/userAttributeMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"ldap/userFederation",
		&module{version},
	)
}
