// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Allows for creating and managing Microsoft OIDC Identity Providers within Keycloak.
 *
 * Microsoft OIDC (OpenID Connect) identity providers allow users to authenticate through Microsoft using the OIDC standard.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as keycloak from "@pulumi/keycloak";
 *
 * const realm = new keycloak.Realm("realm", {
 *     realm: "my-realm",
 *     enabled: true,
 * });
 * const microsoft = new keycloak.oidc.MicrosoftIdentityProvider("microsoft", {
 *     realm: realm.id,
 *     displayName: "myMicrosoft-idp",
 *     clientId: microsoftIdentityProviderClientId,
 *     clientSecret: microsoftIdentityProviderClientSecret,
 *     syncMode: "IMPORT",
 *     extraConfig: {
 *         myCustomConfigKey: "value",
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Microsoft Identity providers can be imported using the format {{realm_id}}/{{idp_alias}}, where idpAlias is the identity provider alias.
 *
 * Example:
 *
 * ```sh
 * $ pulumi import keycloak:oidc/microsoftIdentityProvider:MicrosoftIdentityProvider microsoft my-realm/my-microsoft-idp
 * ```
 */
export class MicrosoftIdentityProvider extends pulumi.CustomResource {
    /**
     * Get an existing MicrosoftIdentityProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MicrosoftIdentityProviderState, opts?: pulumi.CustomResourceOptions): MicrosoftIdentityProvider {
        return new MicrosoftIdentityProvider(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'keycloak:oidc/microsoftIdentityProvider:MicrosoftIdentityProvider';

    /**
     * Returns true if the given object is an instance of MicrosoftIdentityProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MicrosoftIdentityProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MicrosoftIdentityProvider.__pulumiType;
    }

    /**
     * When `true`, unauthenticated requests with `prompt=none` will be forwarded to Microsoft instead of returning an error. Defaults to `false`.
     */
    declare public readonly acceptsPromptNoneForwardFromClient: pulumi.Output<boolean | undefined>;
    /**
     * When `true`, new users will be able to read stored tokens. This will automatically assign the `broker.read-token` role. Defaults to `false`.
     */
    declare public readonly addReadTokenRoleOnCreate: pulumi.Output<boolean | undefined>;
    /**
     * The alias for the Microsoft identity provider.
     */
    declare public readonly alias: pulumi.Output<string>;
    /**
     * Enable/disable authenticate users by default.
     */
    declare public readonly authenticateByDefault: pulumi.Output<boolean | undefined>;
    /**
     * The client or client identifier registered within the identity provider.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * The client or client secret registered within the identity provider. This field is able to obtain its value from vault, use $${vault.ID} format.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * The scopes to be sent when asking for authorization. It can be a space-separated list of scopes. Defaults to `openid profile email`.
     */
    declare public readonly defaultScopes: pulumi.Output<string | undefined>;
    /**
     * When `true`, disables the usage of the user info service to obtain additional user information. Defaults to `false`.
     */
    declare public readonly disableUserInfo: pulumi.Output<boolean | undefined>;
    /**
     * Display name for the Microsoft identity provider in the GUI.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * When `true`, users will be able to log in to this realm using this identity provider. Defaults to `true`.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * A map of key/value pairs to add extra configuration to this identity provider. This can be used for custom oidc provider implementations, or to add configuration that is not yet supported by this Terraform provider. Use this attribute at your own risk, as custom attributes may conflict with top-level configuration attributes in future provider updates.
     */
    declare public readonly extraConfig: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The authentication flow to use when users log in for the first time through this identity provider. Defaults to `first broker login`.
     */
    declare public readonly firstBrokerLoginFlowAlias: pulumi.Output<string | undefined>;
    /**
     * A number defining the order of this identity provider in the GUI.
     */
    declare public readonly guiOrder: pulumi.Output<string | undefined>;
    /**
     * When `true`, this identity provider will be hidden on the login page. Defaults to `false`.
     */
    declare public readonly hideOnLoginPage: pulumi.Output<boolean | undefined>;
    /**
     * (Computed) The unique ID that Keycloak assigns to the identity provider upon creation.
     */
    declare public /*out*/ readonly internalId: pulumi.Output<string>;
    /**
     * When `true`, users cannot sign-in using this provider, but their existing accounts will be linked when possible. Defaults to `false`.
     */
    declare public readonly linkOnly: pulumi.Output<boolean | undefined>;
    declare public readonly orgDomain: pulumi.Output<string | undefined>;
    declare public readonly orgRedirectModeEmailMatches: pulumi.Output<boolean | undefined>;
    /**
     * ID of organization with which this identity is linked.
     */
    declare public readonly organizationId: pulumi.Output<string | undefined>;
    /**
     * The authentication flow to use after users have successfully logged in, which can be used to perform additional user verification (such as OTP checking). Defaults to an empty string, which means no post login flow will be used.
     */
    declare public readonly postBrokerLoginFlowAlias: pulumi.Output<string | undefined>;
    /**
     * Indicates the type of user interaction that is required. The only valid values at this time are `login`, `none`, `consent`, and `selectAccount`.
     */
    declare public readonly prompt: pulumi.Output<string | undefined>;
    /**
     * The ID of the identity provider to use. Defaults to `microsoft`, which should be used unless you have extended Keycloak and provided your own implementation.
     */
    declare public readonly providerId: pulumi.Output<string | undefined>;
    /**
     * The name of the realm. This is unique across Keycloak.
     */
    declare public readonly realm: pulumi.Output<string>;
    /**
     * When `true`, tokens will be stored after authenticating users. Defaults to `true`.
     */
    declare public readonly storeToken: pulumi.Output<boolean | undefined>;
    /**
     * The default sync mode to use for all mappers attached to this identity provider. Can be one of `IMPORT`, `FORCE`, or `LEGACY`.
     */
    declare public readonly syncMode: pulumi.Output<string | undefined>;
    /**
     * Uses single-tenant auth endpoints when specified, uses `common`' multi-tenant endpoints otherwise.
     */
    declare public readonly tenantId: pulumi.Output<string | undefined>;
    /**
     * When `true`, email addresses for users in this provider will automatically be verified regardless of the realm's email verification policy. Defaults to `false`.
     */
    declare public readonly trustEmail: pulumi.Output<boolean | undefined>;

    /**
     * Create a MicrosoftIdentityProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MicrosoftIdentityProviderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MicrosoftIdentityProviderArgs | MicrosoftIdentityProviderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MicrosoftIdentityProviderState | undefined;
            resourceInputs["acceptsPromptNoneForwardFromClient"] = state?.acceptsPromptNoneForwardFromClient;
            resourceInputs["addReadTokenRoleOnCreate"] = state?.addReadTokenRoleOnCreate;
            resourceInputs["alias"] = state?.alias;
            resourceInputs["authenticateByDefault"] = state?.authenticateByDefault;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["clientSecret"] = state?.clientSecret;
            resourceInputs["defaultScopes"] = state?.defaultScopes;
            resourceInputs["disableUserInfo"] = state?.disableUserInfo;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["extraConfig"] = state?.extraConfig;
            resourceInputs["firstBrokerLoginFlowAlias"] = state?.firstBrokerLoginFlowAlias;
            resourceInputs["guiOrder"] = state?.guiOrder;
            resourceInputs["hideOnLoginPage"] = state?.hideOnLoginPage;
            resourceInputs["internalId"] = state?.internalId;
            resourceInputs["linkOnly"] = state?.linkOnly;
            resourceInputs["orgDomain"] = state?.orgDomain;
            resourceInputs["orgRedirectModeEmailMatches"] = state?.orgRedirectModeEmailMatches;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["postBrokerLoginFlowAlias"] = state?.postBrokerLoginFlowAlias;
            resourceInputs["prompt"] = state?.prompt;
            resourceInputs["providerId"] = state?.providerId;
            resourceInputs["realm"] = state?.realm;
            resourceInputs["storeToken"] = state?.storeToken;
            resourceInputs["syncMode"] = state?.syncMode;
            resourceInputs["tenantId"] = state?.tenantId;
            resourceInputs["trustEmail"] = state?.trustEmail;
        } else {
            const args = argsOrState as MicrosoftIdentityProviderArgs | undefined;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.realm === undefined && !opts.urn) {
                throw new Error("Missing required property 'realm'");
            }
            resourceInputs["acceptsPromptNoneForwardFromClient"] = args?.acceptsPromptNoneForwardFromClient;
            resourceInputs["addReadTokenRoleOnCreate"] = args?.addReadTokenRoleOnCreate;
            resourceInputs["alias"] = args?.alias;
            resourceInputs["authenticateByDefault"] = args?.authenticateByDefault;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["defaultScopes"] = args?.defaultScopes;
            resourceInputs["disableUserInfo"] = args?.disableUserInfo;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["extraConfig"] = args?.extraConfig;
            resourceInputs["firstBrokerLoginFlowAlias"] = args?.firstBrokerLoginFlowAlias;
            resourceInputs["guiOrder"] = args?.guiOrder;
            resourceInputs["hideOnLoginPage"] = args?.hideOnLoginPage;
            resourceInputs["linkOnly"] = args?.linkOnly;
            resourceInputs["orgDomain"] = args?.orgDomain;
            resourceInputs["orgRedirectModeEmailMatches"] = args?.orgRedirectModeEmailMatches;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["postBrokerLoginFlowAlias"] = args?.postBrokerLoginFlowAlias;
            resourceInputs["prompt"] = args?.prompt;
            resourceInputs["providerId"] = args?.providerId;
            resourceInputs["realm"] = args?.realm;
            resourceInputs["storeToken"] = args?.storeToken;
            resourceInputs["syncMode"] = args?.syncMode;
            resourceInputs["tenantId"] = args?.tenantId;
            resourceInputs["trustEmail"] = args?.trustEmail;
            resourceInputs["internalId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(MicrosoftIdentityProvider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MicrosoftIdentityProvider resources.
 */
export interface MicrosoftIdentityProviderState {
    /**
     * When `true`, unauthenticated requests with `prompt=none` will be forwarded to Microsoft instead of returning an error. Defaults to `false`.
     */
    acceptsPromptNoneForwardFromClient?: pulumi.Input<boolean | undefined>;
    /**
     * When `true`, new users will be able to read stored tokens. This will automatically assign the `broker.read-token` role. Defaults to `false`.
     */
    addReadTokenRoleOnCreate?: pulumi.Input<boolean | undefined>;
    /**
     * The alias for the Microsoft identity provider.
     */
    alias?: pulumi.Input<string | undefined>;
    /**
     * Enable/disable authenticate users by default.
     */
    authenticateByDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The client or client identifier registered within the identity provider.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * The client or client secret registered within the identity provider. This field is able to obtain its value from vault, use $${vault.ID} format.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * The scopes to be sent when asking for authorization. It can be a space-separated list of scopes. Defaults to `openid profile email`.
     */
    defaultScopes?: pulumi.Input<string | undefined>;
    /**
     * When `true`, disables the usage of the user info service to obtain additional user information. Defaults to `false`.
     */
    disableUserInfo?: pulumi.Input<boolean | undefined>;
    /**
     * Display name for the Microsoft identity provider in the GUI.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * When `true`, users will be able to log in to this realm using this identity provider. Defaults to `true`.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * A map of key/value pairs to add extra configuration to this identity provider. This can be used for custom oidc provider implementations, or to add configuration that is not yet supported by this Terraform provider. Use this attribute at your own risk, as custom attributes may conflict with top-level configuration attributes in future provider updates.
     */
    extraConfig?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The authentication flow to use when users log in for the first time through this identity provider. Defaults to `first broker login`.
     */
    firstBrokerLoginFlowAlias?: pulumi.Input<string | undefined>;
    /**
     * A number defining the order of this identity provider in the GUI.
     */
    guiOrder?: pulumi.Input<string | undefined>;
    /**
     * When `true`, this identity provider will be hidden on the login page. Defaults to `false`.
     */
    hideOnLoginPage?: pulumi.Input<boolean | undefined>;
    /**
     * (Computed) The unique ID that Keycloak assigns to the identity provider upon creation.
     */
    internalId?: pulumi.Input<string | undefined>;
    /**
     * When `true`, users cannot sign-in using this provider, but their existing accounts will be linked when possible. Defaults to `false`.
     */
    linkOnly?: pulumi.Input<boolean | undefined>;
    orgDomain?: pulumi.Input<string | undefined>;
    orgRedirectModeEmailMatches?: pulumi.Input<boolean | undefined>;
    /**
     * ID of organization with which this identity is linked.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The authentication flow to use after users have successfully logged in, which can be used to perform additional user verification (such as OTP checking). Defaults to an empty string, which means no post login flow will be used.
     */
    postBrokerLoginFlowAlias?: pulumi.Input<string | undefined>;
    /**
     * Indicates the type of user interaction that is required. The only valid values at this time are `login`, `none`, `consent`, and `selectAccount`.
     */
    prompt?: pulumi.Input<string | undefined>;
    /**
     * The ID of the identity provider to use. Defaults to `microsoft`, which should be used unless you have extended Keycloak and provided your own implementation.
     */
    providerId?: pulumi.Input<string | undefined>;
    /**
     * The name of the realm. This is unique across Keycloak.
     */
    realm?: pulumi.Input<string | undefined>;
    /**
     * When `true`, tokens will be stored after authenticating users. Defaults to `true`.
     */
    storeToken?: pulumi.Input<boolean | undefined>;
    /**
     * The default sync mode to use for all mappers attached to this identity provider. Can be one of `IMPORT`, `FORCE`, or `LEGACY`.
     */
    syncMode?: pulumi.Input<string | undefined>;
    /**
     * Uses single-tenant auth endpoints when specified, uses `common`' multi-tenant endpoints otherwise.
     */
    tenantId?: pulumi.Input<string | undefined>;
    /**
     * When `true`, email addresses for users in this provider will automatically be verified regardless of the realm's email verification policy. Defaults to `false`.
     */
    trustEmail?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a MicrosoftIdentityProvider resource.
 */
export interface MicrosoftIdentityProviderArgs {
    /**
     * When `true`, unauthenticated requests with `prompt=none` will be forwarded to Microsoft instead of returning an error. Defaults to `false`.
     */
    acceptsPromptNoneForwardFromClient?: pulumi.Input<boolean | undefined>;
    /**
     * When `true`, new users will be able to read stored tokens. This will automatically assign the `broker.read-token` role. Defaults to `false`.
     */
    addReadTokenRoleOnCreate?: pulumi.Input<boolean | undefined>;
    /**
     * The alias for the Microsoft identity provider.
     */
    alias?: pulumi.Input<string | undefined>;
    /**
     * Enable/disable authenticate users by default.
     */
    authenticateByDefault?: pulumi.Input<boolean | undefined>;
    /**
     * The client or client identifier registered within the identity provider.
     */
    clientId: pulumi.Input<string>;
    /**
     * The client or client secret registered within the identity provider. This field is able to obtain its value from vault, use $${vault.ID} format.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * The scopes to be sent when asking for authorization. It can be a space-separated list of scopes. Defaults to `openid profile email`.
     */
    defaultScopes?: pulumi.Input<string | undefined>;
    /**
     * When `true`, disables the usage of the user info service to obtain additional user information. Defaults to `false`.
     */
    disableUserInfo?: pulumi.Input<boolean | undefined>;
    /**
     * Display name for the Microsoft identity provider in the GUI.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * When `true`, users will be able to log in to this realm using this identity provider. Defaults to `true`.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * A map of key/value pairs to add extra configuration to this identity provider. This can be used for custom oidc provider implementations, or to add configuration that is not yet supported by this Terraform provider. Use this attribute at your own risk, as custom attributes may conflict with top-level configuration attributes in future provider updates.
     */
    extraConfig?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The authentication flow to use when users log in for the first time through this identity provider. Defaults to `first broker login`.
     */
    firstBrokerLoginFlowAlias?: pulumi.Input<string | undefined>;
    /**
     * A number defining the order of this identity provider in the GUI.
     */
    guiOrder?: pulumi.Input<string | undefined>;
    /**
     * When `true`, this identity provider will be hidden on the login page. Defaults to `false`.
     */
    hideOnLoginPage?: pulumi.Input<boolean | undefined>;
    /**
     * When `true`, users cannot sign-in using this provider, but their existing accounts will be linked when possible. Defaults to `false`.
     */
    linkOnly?: pulumi.Input<boolean | undefined>;
    orgDomain?: pulumi.Input<string | undefined>;
    orgRedirectModeEmailMatches?: pulumi.Input<boolean | undefined>;
    /**
     * ID of organization with which this identity is linked.
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * The authentication flow to use after users have successfully logged in, which can be used to perform additional user verification (such as OTP checking). Defaults to an empty string, which means no post login flow will be used.
     */
    postBrokerLoginFlowAlias?: pulumi.Input<string | undefined>;
    /**
     * Indicates the type of user interaction that is required. The only valid values at this time are `login`, `none`, `consent`, and `selectAccount`.
     */
    prompt?: pulumi.Input<string | undefined>;
    /**
     * The ID of the identity provider to use. Defaults to `microsoft`, which should be used unless you have extended Keycloak and provided your own implementation.
     */
    providerId?: pulumi.Input<string | undefined>;
    /**
     * The name of the realm. This is unique across Keycloak.
     */
    realm: pulumi.Input<string>;
    /**
     * When `true`, tokens will be stored after authenticating users. Defaults to `true`.
     */
    storeToken?: pulumi.Input<boolean | undefined>;
    /**
     * The default sync mode to use for all mappers attached to this identity provider. Can be one of `IMPORT`, `FORCE`, or `LEGACY`.
     */
    syncMode?: pulumi.Input<string | undefined>;
    /**
     * Uses single-tenant auth endpoints when specified, uses `common`' multi-tenant endpoints otherwise.
     */
    tenantId?: pulumi.Input<string | undefined>;
    /**
     * When `true`, email addresses for users in this provider will automatically be verified regardless of the realm's email verification policy. Defaults to `false`.
     */
    trustEmail?: pulumi.Input<boolean | undefined>;
}
