provider: keycloak
major-version: 6
env: # these are in plaintext in the setup script
    KEYCLOAK_CLIENT_ID: "terraform"
    KEYCLOAK_CLIENT_SECRET: "884e0f95-0f42-4a63-9b1f-94274655669e"
    KEYCLOAK_PASSWORD: "password"
    KEYCLOAK_URL: "http://localhost:8080"
    KEYCLOAK_USER: "keycloak"
makeTemplate: bridged
pulumiConvert: 1
renovateCmd: make tfgen schema build_sdks
registryDocs: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
