provider: keycloak
major-version: 5
env: # these are in plaintext in the setup script
  KEYCLOAK_CLIENT_ID: "terraform"
  KEYCLOAK_CLIENT_SECRET: "884e0f95-0f42-4a63-9b1f-94274655669e"
  KEYCLOAK_PASSWORD: "password"
  KEYCLOAK_URL: "http://localhost:8080"
  KEYCLOAK_USER: "keycloak"
makeTemplate: bridged
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
  - name: aws
    version: "4.2.0"
pulumiConvert: 1
registryDocs: true
