// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Keycloak
{
    /// <summary>
    /// Allows for creating and managing hardcoded group mappers for Keycloak identity provider.
    /// 
    /// The identity provider hardcoded group mapper grants a specified Keycloak group to each Keycloak user from the identity provider.
    /// 
    /// ## Example Usage
    /// </summary>
    [KeycloakResourceType("keycloak:index/hardcodedGroupIdentityProviderMapper:HardcodedGroupIdentityProviderMapper")]
    public partial class HardcodedGroupIdentityProviderMapper : global::Pulumi.CustomResource
    {
        [Output("extraConfig")]
        public Output<ImmutableDictionary<string, string>?> ExtraConfig { get; private set; } = null!;

        /// <summary>
        /// The name of the group which should be assigned to the users.
        /// </summary>
        [Output("group")]
        public Output<string?> Group { get; private set; } = null!;

        /// <summary>
        /// The IDP alias of the attribute to set.
        /// </summary>
        [Output("identityProviderAlias")]
        public Output<string> IdentityProviderAlias { get; private set; } = null!;

        /// <summary>
        /// Display name of this mapper when displayed in the console.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The realm ID that this mapper will exist in.
        /// </summary>
        [Output("realm")]
        public Output<string> Realm { get; private set; } = null!;


        /// <summary>
        /// Create a HardcodedGroupIdentityProviderMapper resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public HardcodedGroupIdentityProviderMapper(string name, HardcodedGroupIdentityProviderMapperArgs args, CustomResourceOptions? options = null)
            : base("keycloak:index/hardcodedGroupIdentityProviderMapper:HardcodedGroupIdentityProviderMapper", name, args ?? new HardcodedGroupIdentityProviderMapperArgs(), MakeResourceOptions(options, ""))
        {
        }

        private HardcodedGroupIdentityProviderMapper(string name, Input<string> id, HardcodedGroupIdentityProviderMapperState? state = null, CustomResourceOptions? options = null)
            : base("keycloak:index/hardcodedGroupIdentityProviderMapper:HardcodedGroupIdentityProviderMapper", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing HardcodedGroupIdentityProviderMapper resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static HardcodedGroupIdentityProviderMapper Get(string name, Input<string> id, HardcodedGroupIdentityProviderMapperState? state = null, CustomResourceOptions? options = null)
        {
            return new HardcodedGroupIdentityProviderMapper(name, id, state, options);
        }
    }

    public sealed class HardcodedGroupIdentityProviderMapperArgs : global::Pulumi.ResourceArgs
    {
        [Input("extraConfig")]
        private InputMap<string>? _extraConfig;
        public InputMap<string> ExtraConfig
        {
            get => _extraConfig ?? (_extraConfig = new InputMap<string>());
            set => _extraConfig = value;
        }

        /// <summary>
        /// The name of the group which should be assigned to the users.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// The IDP alias of the attribute to set.
        /// </summary>
        [Input("identityProviderAlias", required: true)]
        public Input<string> IdentityProviderAlias { get; set; } = null!;

        /// <summary>
        /// Display name of this mapper when displayed in the console.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The realm ID that this mapper will exist in.
        /// </summary>
        [Input("realm", required: true)]
        public Input<string> Realm { get; set; } = null!;

        public HardcodedGroupIdentityProviderMapperArgs()
        {
        }
        public static new HardcodedGroupIdentityProviderMapperArgs Empty => new HardcodedGroupIdentityProviderMapperArgs();
    }

    public sealed class HardcodedGroupIdentityProviderMapperState : global::Pulumi.ResourceArgs
    {
        [Input("extraConfig")]
        private InputMap<string>? _extraConfig;
        public InputMap<string> ExtraConfig
        {
            get => _extraConfig ?? (_extraConfig = new InputMap<string>());
            set => _extraConfig = value;
        }

        /// <summary>
        /// The name of the group which should be assigned to the users.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// The IDP alias of the attribute to set.
        /// </summary>
        [Input("identityProviderAlias")]
        public Input<string>? IdentityProviderAlias { get; set; }

        /// <summary>
        /// Display name of this mapper when displayed in the console.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The realm ID that this mapper will exist in.
        /// </summary>
        [Input("realm")]
        public Input<string>? Realm { get; set; }

        public HardcodedGroupIdentityProviderMapperState()
        {
        }
        public static new HardcodedGroupIdentityProviderMapperState Empty => new HardcodedGroupIdentityProviderMapperState();
    }
}
