// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Allows for creating and managing hardcoded group mappers for Keycloak users federated via LDAP.
 *
 * The LDAP hardcoded group mapper will grant a specified Keycloak group to each Keycloak user linked with LDAP.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as keycloak from "@pulumi/keycloak";
 *
 * const realm = new keycloak.Realm("realm", {
 *     realm: "my-realm",
 *     enabled: true,
 * });
 * const ldapUserFederation = new keycloak.ldap.UserFederation("ldap_user_federation", {
 *     name: "openldap",
 *     realmId: realm.id,
 *     usernameLdapAttribute: "cn",
 *     rdnLdapAttribute: "cn",
 *     uuidLdapAttribute: "entryDN",
 *     userObjectClasses: [
 *         "simpleSecurityObject",
 *         "organizationalRole",
 *     ],
 *     connectionUrl: "ldap://openldap",
 *     usersDn: "dc=example,dc=org",
 *     bindDn: "cn=admin,dc=example,dc=org",
 *     bindCredential: "admin",
 * });
 * const realmGroup = new keycloak.Group("realm_group", {
 *     realmId: realm.id,
 *     name: "my-group",
 * });
 * const assignGroupToUsers = new keycloak.ldap.HardcodedGroupMapper("assign_group_to_users", {
 *     realmId: realm.id,
 *     ldapUserFederationId: ldapUserFederation.id,
 *     name: "assign-group-to-users",
 *     group: realmGroup.name,
 * });
 * ```
 *
 * ## Import
 *
 * LDAP mappers can be imported using the format `{{realm_id}}/{{ldap_user_federation_id}}/{{ldap_mapper_id}}`.
 *
 * The ID of the LDAP user federation provider and the mapper can be found within the Keycloak GUI, and they are typically GUIDs.
 *
 * Example:
 *
 * bash
 *
 * ```sh
 * $ pulumi import keycloak:ldap/hardcodedGroupMapper:HardcodedGroupMapper assign_group_to_users my-realm/af2a6ca3-e4d7-49c3-b08b-1b3c70b4b860/3d923ece-1a91-4bf7-adaf-3b82f2a12b67
 * ```
 */
export class HardcodedGroupMapper extends pulumi.CustomResource {
    /**
     * Get an existing HardcodedGroupMapper resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: HardcodedGroupMapperState, opts?: pulumi.CustomResourceOptions): HardcodedGroupMapper {
        return new HardcodedGroupMapper(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'keycloak:ldap/hardcodedGroupMapper:HardcodedGroupMapper';

    /**
     * Returns true if the given object is an instance of HardcodedGroupMapper.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is HardcodedGroupMapper {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === HardcodedGroupMapper.__pulumiType;
    }

    /**
     * The name of the group which should be assigned to the users.
     */
    declare public readonly group: pulumi.Output<string>;
    /**
     * The ID of the LDAP user federation provider to attach this mapper to.
     */
    declare public readonly ldapUserFederationId: pulumi.Output<string>;
    /**
     * Display name of this mapper when displayed in the console.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The realm that this LDAP mapper will exist in.
     */
    declare public readonly realmId: pulumi.Output<string>;

    /**
     * Create a HardcodedGroupMapper resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: HardcodedGroupMapperArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: HardcodedGroupMapperArgs | HardcodedGroupMapperState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as HardcodedGroupMapperState | undefined;
            resourceInputs["group"] = state?.group;
            resourceInputs["ldapUserFederationId"] = state?.ldapUserFederationId;
            resourceInputs["name"] = state?.name;
            resourceInputs["realmId"] = state?.realmId;
        } else {
            const args = argsOrState as HardcodedGroupMapperArgs | undefined;
            if (args?.group === undefined && !opts.urn) {
                throw new Error("Missing required property 'group'");
            }
            if (args?.ldapUserFederationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'ldapUserFederationId'");
            }
            if (args?.realmId === undefined && !opts.urn) {
                throw new Error("Missing required property 'realmId'");
            }
            resourceInputs["group"] = args?.group;
            resourceInputs["ldapUserFederationId"] = args?.ldapUserFederationId;
            resourceInputs["name"] = args?.name;
            resourceInputs["realmId"] = args?.realmId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(HardcodedGroupMapper.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering HardcodedGroupMapper resources.
 */
export interface HardcodedGroupMapperState {
    /**
     * The name of the group which should be assigned to the users.
     */
    group?: pulumi.Input<string>;
    /**
     * The ID of the LDAP user federation provider to attach this mapper to.
     */
    ldapUserFederationId?: pulumi.Input<string>;
    /**
     * Display name of this mapper when displayed in the console.
     */
    name?: pulumi.Input<string>;
    /**
     * The realm that this LDAP mapper will exist in.
     */
    realmId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a HardcodedGroupMapper resource.
 */
export interface HardcodedGroupMapperArgs {
    /**
     * The name of the group which should be assigned to the users.
     */
    group: pulumi.Input<string>;
    /**
     * The ID of the LDAP user federation provider to attach this mapper to.
     */
    ldapUserFederationId: pulumi.Input<string>;
    /**
     * Display name of this mapper when displayed in the console.
     */
    name?: pulumi.Input<string>;
    /**
     * The realm that this LDAP mapper will exist in.
     */
    realmId: pulumi.Input<string>;
}
