// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.keycloak.saml;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.keycloak.Utilities;
import com.pulumi.keycloak.saml.ClientScopeArgs;
import com.pulumi.keycloak.saml.inputs.ClientScopeState;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Allows for creating and managing Keycloak client scopes that can be attached to clients that use the SAML protocol.
 * 
 * Client Scopes can be used to share common protocol and role mappings between multiple clients within a realm.
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.keycloak.Realm;
 * import com.pulumi.keycloak.RealmArgs;
 * import com.pulumi.keycloak.saml.ClientScope;
 * import com.pulumi.keycloak.saml.ClientScopeArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var realm = new Realm("realm", RealmArgs.builder()
 *             .realm("my-realm")
 *             .enabled(true)
 *             .build());
 * 
 *         var samlClientScope = new ClientScope("samlClientScope", ClientScopeArgs.builder()
 *             .realmId(realm.id())
 *             .name("groups")
 *             .description("This scope will map a user's group memberships to SAML assertion")
 *             .guiOrder(1)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * Client scopes can be imported using the format `{{realm_id}}/{{client_scope_id}}`, where `clientScopeId` is the unique ID that Keycloak
 * assigns to the client scope upon creation. This value can be found in the URI when editing this client scope in the GUI, and is typically a GUID.
 * 
 * Example:
 * 
 */
@ResourceType(type="keycloak:saml/clientScope:ClientScope")
public class ClientScope extends com.pulumi.resources.CustomResource {
    /**
     * When set, a consent screen will be displayed to users authenticating to clients with this scope attached. The consent screen will display the string value of this attribute.
     * 
     */
    @Export(name="consentScreenText", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> consentScreenText;

    /**
     * @return When set, a consent screen will be displayed to users authenticating to clients with this scope attached. The consent screen will display the string value of this attribute.
     * 
     */
    public Output<Optional<String>> consentScreenText() {
        return Codegen.optional(this.consentScreenText);
    }
    /**
     * The description of this client scope in the GUI.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description of this client scope in the GUI.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * A map of key/value pairs to add extra configuration attributes to this client scope. This can be used for custom attributes or to add configuration attributes that are not yet supported by this Terraform provider. Use this attribute at your own risk, as it may conflict with top-level configuration attributes in future provider updates.
     * 
     */
    @Export(name="extraConfig", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extraConfig;

    /**
     * @return A map of key/value pairs to add extra configuration attributes to this client scope. This can be used for custom attributes or to add configuration attributes that are not yet supported by this Terraform provider. Use this attribute at your own risk, as it may conflict with top-level configuration attributes in future provider updates.
     * 
     */
    public Output<Optional<Map<String,String>>> extraConfig() {
        return Codegen.optional(this.extraConfig);
    }
    /**
     * Specify order of the client scope in GUI (such as in Consent page) as integer.
     * 
     */
    @Export(name="guiOrder", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> guiOrder;

    /**
     * @return Specify order of the client scope in GUI (such as in Consent page) as integer.
     * 
     */
    public Output<Optional<Integer>> guiOrder() {
        return Codegen.optional(this.guiOrder);
    }
    /**
     * The display name of this client scope in the GUI.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The display name of this client scope in the GUI.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The realm this client scope belongs to.
     * 
     */
    @Export(name="realmId", refs={String.class}, tree="[0]")
    private Output<String> realmId;

    /**
     * @return The realm this client scope belongs to.
     * 
     */
    public Output<String> realmId() {
        return this.realmId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ClientScope(java.lang.String name) {
        this(name, ClientScopeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ClientScope(java.lang.String name, ClientScopeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ClientScope(java.lang.String name, ClientScopeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("keycloak:saml/clientScope:ClientScope", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ClientScope(java.lang.String name, Output<java.lang.String> id, @Nullable ClientScopeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("keycloak:saml/clientScope:ClientScope", name, state, makeResourceOptions(options, id), false);
    }

    private static ClientScopeArgs makeArgs(ClientScopeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ClientScopeArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ClientScope get(java.lang.String name, Output<java.lang.String> id, @Nullable ClientScopeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ClientScope(name, id, state, options);
    }
}
