// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package keycloak

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-keycloak/sdk/v6/go/keycloak/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source can be used to fetch properties of a Keycloak group for
// usage with other resources, such as `GroupRoles`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-keycloak/sdk/v6/go/keycloak"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			realm, err := keycloak.NewRealm(ctx, "realm", &keycloak.RealmArgs{
//				Realm:   pulumi.String("my-realm"),
//				Enabled: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			offlineAccess := keycloak.GetRoleOutput(ctx, keycloak.GetRoleOutputArgs{
//				RealmId: realm.ID(),
//				Name:    pulumi.String("offline_access"),
//			}, nil)
//			group := keycloak.GetGroupOutput(ctx, keycloak.GetGroupOutputArgs{
//				RealmId: realm.ID(),
//				Name:    pulumi.String("group"),
//			}, nil)
//			_, err = keycloak.NewGroupRoles(ctx, "group_roles", &keycloak.GroupRolesArgs{
//				RealmId: realm.ID(),
//				GroupId: pulumi.String(group.ApplyT(func(group keycloak.GetGroupResult) (*string, error) {
//					return group.Id, nil
//				}).(pulumi.StringPtrOutput)),
//				RoleIds: pulumi.StringArray{
//					pulumi.String(offlineAccess.ApplyT(func(offlineAccess keycloak.GetRoleResult) (*string, error) {
//						return offlineAccess.Id, nil
//					}).(pulumi.StringPtrOutput)),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Using group_path to look up nested groups by their full path
//			superAdmin := keycloak.GetRoleOutput(ctx, keycloak.GetRoleOutputArgs{
//				RealmId: realm.ID(),
//				Name:    pulumi.String("super_admin"),
//			}, nil)
//			admins := keycloak.GetGroupOutput(ctx, keycloak.GetGroupOutputArgs{
//				RealmId:   realm.ID(),
//				GroupPath: pulumi.String("/Administration/Full Admins"),
//			}, nil)
//			_, err = keycloak.NewGroupRoles(ctx, "admins_roles", &keycloak.GroupRolesArgs{
//				RealmId: realm.ID(),
//				GroupId: pulumi.String(admins.ApplyT(func(admins keycloak.GetGroupResult) (*string, error) {
//					return admins.Id, nil
//				}).(pulumi.StringPtrOutput)),
//				RoleIds: pulumi.StringArray{
//					pulumi.String(superAdmin.ApplyT(func(superAdmin keycloak.GetRoleResult) (*string, error) {
//						return superAdmin.Id, nil
//					}).(pulumi.StringPtrOutput)),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// Organization groups can be looked up by setting `organizationId`. Organization groups require Keycloak 26.6.0 or later.
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-keycloak/sdk/v6/go/keycloak"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := keycloak.GetGroup(ctx, &keycloak.LookupGroupArgs{
//				RealmId:        realm.Id,
//				OrganizationId: pulumi.StringRef(organization.Id),
//				Name:           pulumi.StringRef("organization-group"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupGroup(ctx *pulumi.Context, args *LookupGroupArgs, opts ...pulumi.InvokeOption) (*LookupGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGroupResult
	err := ctx.Invoke("keycloak:index/getGroup:getGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGroup.
type LookupGroupArgs struct {
	Description *string `pulumi:"description"`
	// The full path of the group (e.g. `"/parent/child/subgroup"`). Mutually exclusive with `name`. This uses the Keycloak `/group-by-path` endpoint for a precise lookup.
	GroupPath *string `pulumi:"groupPath"`
	// The name of the group. Mutually exclusive with `groupPath`. If there are multiple groups matching `name`, the first result is returned.
	Name *string `pulumi:"name"`
	// The organization this group exists within. If omitted, the data source looks up realm groups.
	OrganizationId *string `pulumi:"organizationId"`
	// The realm this group exists within.
	RealmId string `pulumi:"realmId"`
}

// A collection of values returned by getGroup.
type LookupGroupResult struct {
	Attributes  map[string]string `pulumi:"attributes"`
	Description *string           `pulumi:"description"`
	GroupPath   *string           `pulumi:"groupPath"`
	// The provider-assigned unique ID for this managed resource.
	Id             string  `pulumi:"id"`
	Name           *string `pulumi:"name"`
	OrganizationId *string `pulumi:"organizationId"`
	ParentId       string  `pulumi:"parentId"`
	Path           string  `pulumi:"path"`
	RealmId        string  `pulumi:"realmId"`
}

func LookupGroupOutput(ctx *pulumi.Context, args LookupGroupOutputArgs, opts ...pulumi.InvokeOption) LookupGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupGroupResultOutput, error) {
			args := v.(LookupGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("keycloak:index/getGroup:getGroup", args, LookupGroupResultOutput{}, options).(LookupGroupResultOutput), nil
		}).(LookupGroupResultOutput)
}

// A collection of arguments for invoking getGroup.
type LookupGroupOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The full path of the group (e.g. `"/parent/child/subgroup"`). Mutually exclusive with `name`. This uses the Keycloak `/group-by-path` endpoint for a precise lookup.
	GroupPath pulumi.StringPtrInput `pulumi:"groupPath"`
	// The name of the group. Mutually exclusive with `groupPath`. If there are multiple groups matching `name`, the first result is returned.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The organization this group exists within. If omitted, the data source looks up realm groups.
	OrganizationId pulumi.StringPtrInput `pulumi:"organizationId"`
	// The realm this group exists within.
	RealmId pulumi.StringInput `pulumi:"realmId"`
}

func (LookupGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGroupArgs)(nil)).Elem()
}

// A collection of values returned by getGroup.
type LookupGroupResultOutput struct{ *pulumi.OutputState }

func (LookupGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGroupResult)(nil)).Elem()
}

func (o LookupGroupResultOutput) ToLookupGroupResultOutput() LookupGroupResultOutput {
	return o
}

func (o LookupGroupResultOutput) ToLookupGroupResultOutputWithContext(ctx context.Context) LookupGroupResultOutput {
	return o
}

func (o LookupGroupResultOutput) Attributes() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupGroupResult) map[string]string { return v.Attributes }).(pulumi.StringMapOutput)
}

func (o LookupGroupResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

func (o LookupGroupResultOutput) GroupPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *string { return v.GroupPath }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupGroupResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupGroupResultOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *string { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

func (o LookupGroupResultOutput) ParentId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.ParentId }).(pulumi.StringOutput)
}

func (o LookupGroupResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o LookupGroupResultOutput) RealmId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.RealmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGroupResultOutput{})
}
