// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package keycloak

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "keycloak:index/attributeImporterIdentityProviderMapper:AttributeImporterIdentityProviderMapper":
		r, err = NewAttributeImporterIdentityProviderMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/attributeToRoleIdentityMapper:AttributeToRoleIdentityMapper":
		r, err = NewAttributeToRoleIdentityMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/customUserFederation:CustomUserFederation":
		r, err = NewCustomUserFederation(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/defaultGroups:DefaultGroups":
		r, err = NewDefaultGroups(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/genericClientProtocolMapper:GenericClientProtocolMapper":
		r, err = NewGenericClientProtocolMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/genericClientRoleMapper:GenericClientRoleMapper":
		r, err = NewGenericClientRoleMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/group:Group":
		r, err = NewGroup(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/groupMemberships:GroupMemberships":
		r, err = NewGroupMemberships(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/groupRoles:GroupRoles":
		r, err = NewGroupRoles(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/hardcodedAttributeIdentityProviderMapper:HardcodedAttributeIdentityProviderMapper":
		r, err = NewHardcodedAttributeIdentityProviderMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/hardcodedRoleIdentityMapper:HardcodedRoleIdentityMapper":
		r, err = NewHardcodedRoleIdentityMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/identityProviderTokenExchangeScopePermission:IdentityProviderTokenExchangeScopePermission":
		r, err = NewIdentityProviderTokenExchangeScopePermission(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/realm:Realm":
		r, err = NewRealm(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/realmEvents:RealmEvents":
		r, err = NewRealmEvents(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/requiredAction:RequiredAction":
		r, err = NewRequiredAction(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/role:Role":
		r, err = NewRole(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/user:User":
		r, err = NewUser(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/userRoles:UserRoles":
		r, err = NewUserRoles(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/userTemplateImporterIdentityProviderMapper:UserTemplateImporterIdentityProviderMapper":
		r, err = NewUserTemplateImporterIdentityProviderMapper(ctx, name, nil, pulumi.URN_(urn))
	case "keycloak:index/usersPermissions:UsersPermissions":
		r, err = NewUsersPermissions(ctx, name, nil, pulumi.URN_(urn))
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:keycloak" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	return NewProvider(ctx, name, nil, pulumi.URN_(urn))
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/attributeImporterIdentityProviderMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/attributeToRoleIdentityMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/customUserFederation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/defaultGroups",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/genericClientProtocolMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/genericClientRoleMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/groupMemberships",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/groupRoles",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/hardcodedAttributeIdentityProviderMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/hardcodedRoleIdentityMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/identityProviderTokenExchangeScopePermission",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/realm",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/realmEvents",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/requiredAction",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/userRoles",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/userTemplateImporterIdentityProviderMapper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"keycloak",
		"index/usersPermissions",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"keycloak",
		&pkg{version},
	)
}
