// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * This data source can be used to fetch the details of an authentication subflow within Keycloak.
 *
 * An authentication subflow is a nested flow within a parent authentication flow that groups related authentication steps together.
 *
 * ## Example Usage
 *
 * ### Lookup by Alias (Human-readable)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as keycloak from "@pulumi/keycloak";
 *
 * const realm = new keycloak.Realm("realm", {
 *     realm: "my-realm",
 *     enabled: true,
 * });
 * const myFlow = new keycloak.authentication.Flow("my_flow", {
 *     realmId: realm.id,
 *     alias: "my-custom-flow",
 * });
 * const mySubflow = new keycloak.authentication.Subflow("my_subflow", {
 *     realmId: realm.id,
 *     parentFlowAlias: myFlow.alias,
 *     alias: "my-subflow",
 *     providerId: "basic-flow",
 * });
 * const subflow = keycloak.authentication.getSubflowOutput({
 *     realmId: realm.id,
 *     parentFlowAlias: myFlow.alias,
 *     alias: "my-subflow",
 * });
 * export const subflowId = subflow.apply(subflow => subflow.id);
 * ```
 *
 * ### Lookup by ID (Direct)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as keycloak from "@pulumi/keycloak";
 *
 * const subflow = keycloak.authentication.getSubflow({
 *     realmId: "my-realm-id",
 *     parentFlowAlias: "browser",
 *     id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 * });
 * export const subflowAlias = subflow.then(subflow => subflow.alias);
 * ```
 */
export function getSubflow(args: GetSubflowArgs, opts?: pulumi.InvokeOptions): Promise<GetSubflowResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("keycloak:authentication/getSubflow:getSubflow", {
        "alias": args.alias,
        "id": args.id,
        "parentFlowAlias": args.parentFlowAlias,
        "realmId": args.realmId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubflow.
 */
export interface GetSubflowArgs {
    /**
     * The alias of the authentication subflow. Either `id` or `alias` must be specified.
     *
     * > **Note:** You must specify either `id` or `alias`, but not both. Use `id` for direct lookup by GUID, or `alias` for human-readable lookup by name.
     */
    alias?: string;
    /**
     * The unique ID of the authentication subflow. Either `id` or `alias` must be specified.
     */
    id?: string;
    /**
     * The alias of the parent authentication flow.
     */
    parentFlowAlias: string;
    /**
     * The realm the authentication subflow exists in.
     */
    realmId: string;
}

/**
 * A collection of values returned by getSubflow.
 */
export interface GetSubflowResult {
    /**
     * The alias of the subflow.
     */
    readonly alias?: string;
    readonly authenticator: string;
    /**
     * The description of the subflow.
     */
    readonly description: string;
    /**
     * The unique ID of the authentication subflow.
     */
    readonly id: string;
    readonly parentFlowAlias: string;
    /**
     * (Keycloak 25+) The priority of the subflow within its parent flow.
     */
    readonly priority: number;
    /**
     * The provider ID for the subflow (e.g., `basic-flow`, `form-flow`, or `client-flow`).
     */
    readonly providerId: string;
    readonly realmId: string;
    /**
     * The requirement setting for the subflow. Can be one of `REQUIRED`, `ALTERNATIVE`, `OPTIONAL`, `CONDITIONAL`, or `DISABLED`.
     */
    readonly requirement: string;
}
/**
 * This data source can be used to fetch the details of an authentication subflow within Keycloak.
 *
 * An authentication subflow is a nested flow within a parent authentication flow that groups related authentication steps together.
 *
 * ## Example Usage
 *
 * ### Lookup by Alias (Human-readable)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as keycloak from "@pulumi/keycloak";
 *
 * const realm = new keycloak.Realm("realm", {
 *     realm: "my-realm",
 *     enabled: true,
 * });
 * const myFlow = new keycloak.authentication.Flow("my_flow", {
 *     realmId: realm.id,
 *     alias: "my-custom-flow",
 * });
 * const mySubflow = new keycloak.authentication.Subflow("my_subflow", {
 *     realmId: realm.id,
 *     parentFlowAlias: myFlow.alias,
 *     alias: "my-subflow",
 *     providerId: "basic-flow",
 * });
 * const subflow = keycloak.authentication.getSubflowOutput({
 *     realmId: realm.id,
 *     parentFlowAlias: myFlow.alias,
 *     alias: "my-subflow",
 * });
 * export const subflowId = subflow.apply(subflow => subflow.id);
 * ```
 *
 * ### Lookup by ID (Direct)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as keycloak from "@pulumi/keycloak";
 *
 * const subflow = keycloak.authentication.getSubflow({
 *     realmId: "my-realm-id",
 *     parentFlowAlias: "browser",
 *     id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 * });
 * export const subflowAlias = subflow.then(subflow => subflow.alias);
 * ```
 */
export function getSubflowOutput(args: GetSubflowOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSubflowResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("keycloak:authentication/getSubflow:getSubflow", {
        "alias": args.alias,
        "id": args.id,
        "parentFlowAlias": args.parentFlowAlias,
        "realmId": args.realmId,
    }, opts);
}

/**
 * A collection of arguments for invoking getSubflow.
 */
export interface GetSubflowOutputArgs {
    /**
     * The alias of the authentication subflow. Either `id` or `alias` must be specified.
     *
     * > **Note:** You must specify either `id` or `alias`, but not both. Use `id` for direct lookup by GUID, or `alias` for human-readable lookup by name.
     */
    alias?: pulumi.Input<string>;
    /**
     * The unique ID of the authentication subflow. Either `id` or `alias` must be specified.
     */
    id?: pulumi.Input<string>;
    /**
     * The alias of the parent authentication flow.
     */
    parentFlowAlias: pulumi.Input<string>;
    /**
     * The realm the authentication subflow exists in.
     */
    realmId: pulumi.Input<string>;
}
