// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.keycloak;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.keycloak.RealmClientRegistrationPolicyArgs;
import com.pulumi.keycloak.Utilities;
import com.pulumi.keycloak.inputs.RealmClientRegistrationPolicyState;
import java.lang.String;
import java.util.Map;
import javax.annotation.Nullable;

/**
 * Allows for managing Realm Client Registration Policies.
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.keycloak.Realm;
 * import com.pulumi.keycloak.RealmArgs;
 * import com.pulumi.keycloak.RealmClientRegistrationPolicy;
 * import com.pulumi.keycloak.RealmClientRegistrationPolicyArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var realm = new Realm("realm", RealmArgs.builder()
 *             .realm("my-realm")
 *             .build());
 * 
 *         var custom = new RealmClientRegistrationPolicy("custom", RealmClientRegistrationPolicyArgs.builder()
 *             .realmId(realm.id())
 *             .name("My Custom Policy")
 *             .providerId("my-client-registration-policy")
 *             .subType("anonymous")
 *             .build());
 * 
 *         // A built-in policy with multi-value config (trusted-hosts is an array in Keycloak)
 *         var trustedHosts = new RealmClientRegistrationPolicy("trustedHosts", RealmClientRegistrationPolicyArgs.builder()
 *             .realmId(realm.id())
 *             .name("Trusted Hosts")
 *             .providerId("trusted-hosts")
 *             .subType("anonymous")
 *             .config(Map.ofEntries(
 *                 Map.entry("host-sending-registration-request-must-match", "true"),
 *                 Map.entry("client-uris-must-match", "true"),
 *                 Map.entry("trusted-hosts", "localhost,auth.example.com")
 *             ))
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ### Attribute Arguments
 * 
 * - `name` - (Required) Display name of the policy.
 * - `realmId` - (Required) The realm this policy exists in.
 * - `providerId` - (Required) The ID of the policy provider (e.g. `trusted-hosts`, `max-clients`). The referenced provider must already be registered in Keycloak.
 * - `subType` - (Required) Whether this policy applies to `anonymous` or `authenticated` client registration.
 * - `config` - (Optional) A map of provider-specific configuration values.
 * 
 * #### Multi-value configuration
 * 
 * Some policy config fields store a list of values rather than a single value (for the built-in
 * policies these are `trusted-hosts`, `allowed-client-scopes` and `allowed-protocol-mapper-types`).
 * Supply these as a single comma-separated string, e.g.
 * `&#34;trusted-hosts&#34; = &#34;localhost,auth.example.com&#34;`. The provider splits the value into the array
 * Keycloak expects on write and re-joins it on read. Because Keycloak does not preserve element
 * order, a pure reorder of these values is treated as a no-op and does not produce a perpetual
 * diff.
 * 
 * Which fields are multi-valued is detected automatically from Keycloak&#39;s policy provider
 * metadata (properties reported with a `type` of `MultivaluedString` or `MultivaluedList`), so
 * this works for any provider — including custom SPI policies — without a hardcoded list.
 * 
 * ## Import
 * 
 * Client registration policies can be imported using either of the following formats.
 * 
 * By realm name and policy ID:
 * 
 * ```sh
 * $ pulumi import keycloak:index/realmClientRegistrationPolicy:RealmClientRegistrationPolicy custom my-realm/618cfba7-49aa-4c09-9a19-2f699b576f0b
 * ```
 * 
 * By realm name, policy name, provider ID and sub-type (`{realmId}/{name}/{providerId}/{subType}`).
 * This is useful for taking ownership of the default policies Keycloak auto-creates, whose
 * server-generated UUID is not known ahead of time:
 * 
 * ```sh
 * $ terraform import keycloak_realm_client_registration_policy.trusted_hosts &#34;my-realm/Trusted Hosts/trusted-hosts/anonymous&#34;
 * ```
 * 
 * Note: Keycloak automatically creates default policies for every realm (e.g. &#34;Trusted Hosts&#34;, &#34;Max Clients Limit&#34;).
 * These can be managed by importing them first and then removing the resource block to delete them. The
 * `keycloak.RealmClientRegistrationPolicy` data source can also be used to look one up dynamically.
 * 
 */
@ResourceType(type="keycloak:index/realmClientRegistrationPolicy:RealmClientRegistrationPolicy")
public class RealmClientRegistrationPolicy extends com.pulumi.resources.CustomResource {
    /**
     * Policy-specific configuration key-value pairs.
     * 
     */
    @Export(name="config", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> config;

    /**
     * @return Policy-specific configuration key-value pairs.
     * 
     */
    public Output<Map<String,String>> config() {
        return this.config;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    /**
     * The provider ID of the client registration policy (e.g. &#39;trusted-hosts&#39;, &#39;consent-required&#39;).
     * 
     */
    @Export(name="providerId", refs={String.class}, tree="[0]")
    private Output<String> providerId;

    /**
     * @return The provider ID of the client registration policy (e.g. &#39;trusted-hosts&#39;, &#39;consent-required&#39;).
     * 
     */
    public Output<String> providerId() {
        return this.providerId;
    }
    @Export(name="realmId", refs={String.class}, tree="[0]")
    private Output<String> realmId;

    public Output<String> realmId() {
        return this.realmId;
    }
    /**
     * Whether this policy applies to anonymous or authenticated client registration.
     * 
     */
    @Export(name="subType", refs={String.class}, tree="[0]")
    private Output<String> subType;

    /**
     * @return Whether this policy applies to anonymous or authenticated client registration.
     * 
     */
    public Output<String> subType() {
        return this.subType;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RealmClientRegistrationPolicy(java.lang.String name) {
        this(name, RealmClientRegistrationPolicyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RealmClientRegistrationPolicy(java.lang.String name, RealmClientRegistrationPolicyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RealmClientRegistrationPolicy(java.lang.String name, RealmClientRegistrationPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("keycloak:index/realmClientRegistrationPolicy:RealmClientRegistrationPolicy", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RealmClientRegistrationPolicy(java.lang.String name, Output<java.lang.String> id, @Nullable RealmClientRegistrationPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("keycloak:index/realmClientRegistrationPolicy:RealmClientRegistrationPolicy", name, state, makeResourceOptions(options, id), false);
    }

    private static RealmClientRegistrationPolicyArgs makeArgs(RealmClientRegistrationPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RealmClientRegistrationPolicyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RealmClientRegistrationPolicy get(java.lang.String name, Output<java.lang.String> id, @Nullable RealmClientRegistrationPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RealmClientRegistrationPolicy(name, id, state, options);
    }
}
