// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Keycloak.Inputs
{

    public sealed class GetRealmSmtpServerArgs : global::Pulumi.InvokeArgs
    {
        [Input("auths", required: true)]
        private List<Inputs.GetRealmSmtpServerAuthArgs>? _auths;
        public List<Inputs.GetRealmSmtpServerAuthArgs> Auths
        {
            get => _auths ?? (_auths = new List<Inputs.GetRealmSmtpServerAuthArgs>());
            set => _auths = value;
        }

        [Input("envelopeFrom", required: true)]
        public string EnvelopeFrom { get; set; } = null!;

        [Input("from", required: true)]
        public string From { get; set; } = null!;

        [Input("fromDisplayName", required: true)]
        public string FromDisplayName { get; set; } = null!;

        [Input("host", required: true)]
        public string Host { get; set; } = null!;

        [Input("port", required: true)]
        public string Port { get; set; } = null!;

        [Input("replyTo", required: true)]
        public string ReplyTo { get; set; } = null!;

        [Input("replyToDisplayName", required: true)]
        public string ReplyToDisplayName { get; set; } = null!;

        [Input("ssl", required: true)]
        public bool Ssl { get; set; }

        [Input("starttls", required: true)]
        public bool Starttls { get; set; }

        [Input("tokenAuths", required: true)]
        private List<Inputs.GetRealmSmtpServerTokenAuthArgs>? _tokenAuths;
        public List<Inputs.GetRealmSmtpServerTokenAuthArgs> TokenAuths
        {
            get => _tokenAuths ?? (_tokenAuths = new List<Inputs.GetRealmSmtpServerTokenAuthArgs>());
            set => _tokenAuths = value;
        }

        public GetRealmSmtpServerArgs()
        {
        }
        public static new GetRealmSmtpServerArgs Empty => new GetRealmSmtpServerArgs();
    }
}
